- quizmaster-client-app/src/components/QuizHosting/QuestionMarker.tsx
- quizmaster-client-app/src/components/QuizHosting/QuizHoster.tsx
Toggles have been added instead of check boxes and a FAB (floating action button) has been used instead of the small grey button. The changes made closes #11.
> feat(webapp): enhanced quiz marking screen with toggles and FAB 

- QuizMaster.Api/Controllers/ContestantsController.cs
- QuizMaster.Api/Controllers/QuizzesController.cs
- QuizMaster.Api/Postman Tests/Quiz Master API Tests.postman_collection.json
- QuizMaster.Application/Contestants/Create.cs
- quizmaster-client-app/src/app/layout/App.tsx
- quizmaster-client-app/src/components/Common/NotFound.css
- quizmaster-client-app/src/components/Common/NotFound.test.tsx
- quizmaster-client-app/src/components/Common/NotFound.tsx
- quizmaster-client-app/src/components/QuizHosting/HostLobby.tsx
- quizmaster-client-app/src/components/QuizParticipating/QuizJoiner.tsx
I've added a ```NotFound``` component for use when a route doesn't match any other component and the quiz joining component wont load the input for the name if the quiz doesn't exist, it will notify the user. closes #4
> Handle quiz not found when joining and added a generic not found for general cases

- .gitignore
- QuizMaster.Api/Postman Tests/Quiz Master API Tests.postman_collection.json
- quizmaster-client-app/cypress/integration/createquiz.ts
- quizmaster-client-app/cypress/integration/homepage.ts
- quizmaster-client-app/cypress/integration/joinquiz.ts
- quizmaster-client-app/cypress/plugins/index.js
- quizmaster-client-app/cypress/support/index.js
- quizmaster-client-app/package.json
- quizmaster-client-app/src/components/HomePage/HomePage.tsx
- quizmaster-client-app/src/components/QuizHosting/QuizWizard.tsx
- quizmaster-client-app/src/components/QuizParticipating/QuizJoiner.tsx
> Added cypress tests for basic quiz joining and creating

- QuizMaster.Api/QuizMaster.Api.csproj
- QuizMaster.Application/Questions/List.cs
- QuizMaster.Application/QuizMaster.Application.csproj
- QuizMaster.Application/Quizzes/Details.cs
- QuizMaster.Domain/QuizMaster.Domain.csproj
- QuizMaster.Persistence/QuizMaster.Persistence.csproj
> Treat errors as warnings

- quizmaster-client-app/src/app/layout/App.tsx
- quizmaster-client-app/src/components/HomePage/HomePage.tsx
- quizmaster-client-app/src/components/QuizParticipating/QuestionResponder.tsx
- quizmaster-client-app/src/components/QuizParticipating/QuizJoiner.tsx
> Tidied participant URL structure by putting participant ID in local storage.

- quizmaster-client-app/src/components/HomePage/HomePage.tsx
Centered icons on the homepage, moved join quiz to top and made host quiz the secondary action.
> Homepage UX

- QuizMaster.Api/Controllers/ContestantsController.cs
- QuizMaster.Api/Controllers/QuizzesController.cs
- QuizMaster.Api/Filters/ApiKeyAuthAttribute.cs
- QuizMaster.Api/Postman Tests/Quiz Master API Tests.postman_collection.json
- QuizMaster.Api/Startup.cs
- QuizMaster.Application/Contestants/Create.cs
- QuizMaster.Application/Contestants/Details.cs
- QuizMaster.Application/ParticipantMessage.cs
- QuizMaster.Application/QuizMasterMessage.cs
- QuizMaster.Domain/Quiz.cs
- QuizMaster.Persistence/Migrations/20200615090231_QuizApiKey.Designer.cs
- QuizMaster.Persistence/Migrations/20200615090231_QuizApiKey.cs
- quizmaster-client-app/src/components/HomePage/HomePage.tsx
- quizmaster-client-app/src/components/QuizParticipating/QuizJoiner.tsx
Secured endpoints that should only be used by the quiz master and updated postman tests. closes #30
> Quiz master endpoint security

- QuizMaster.Api/Controllers/QuizzesController.cs
- quizmaster-client-app/src/components/QuizHosting/QuestionCreator/QuestionCreator.test.tsx
- quizmaster-client-app/src/components/QuizHosting/QuestionCreator/QuestionReducer.ts
> Fixed problem with updating quiz questions

- quizmaster-client-app/src/components/Common/Footer.tsx
- quizmaster-client-app/src/components/QuizHosting/HostLobby.tsx
- quizmaster-client-app/src/components/QuizHosting/QuestionCreator/QuestionCreator.tsx
- quizmaster-client-app/src/components/QuizHosting/QuestionCreator/QuestionReducer.ts
- quizmaster-client-app/src/components/QuizHosting/QuizHoster.tsx
- quizmaster-client-app/src/components/QuizHosting/QuizWizard.tsx
- quizmaster-client-app/src/components/QuizParticipating/QuestionResponder.tsx
- quizmaster-client-app/src/components/QuizParticipating/QuizJoiner.tsx
- quizmaster-client-app/src/stringUtilities.ts
> Fix build warnings

- quizmaster-client-app/src/index.tsx
> Set api key globally when the page reloads

- quizmaster-client-app/cypress/integration/createquiz.ts
- quizmaster-client-app/src/components/QuizHosting/QuestionCreator/QuestionCreator.tsx
- quizmaster-client-app/src/components/QuizHosting/QuestionCreator/QuestionInitialiser.test.tsx
- quizmaster-client-app/src/components/QuizHosting/QuestionCreator/QuestionInitialiser.tsx
> Empty state component for creating the first question

- quizmaster-client-app/cypress/integration/createquiz.ts
> Enable all e2e tests

- quizmaster-client-app/package-lock.json
- quizmaster-client-app/package.json
- quizmaster-client-app/src/components/QuizHosting/QuestionCreator/QuestionCreator.test.tsx
> Fixed question creator tests that were failing due to axios not being mocked

- quizmaster-client-app/src/components/QuizHosting/QuestionCreator/QuestionCreator.tsx
- quizmaster-client-app/src/components/QuizHosting/QuestionCreator/TableFieldEditor.tsx
> Custom table inputs for questions and answers and moved row buttons to right of table row

- quizmaster-client-app/cypress/integration/createquiz.ts
- quizmaster-client-app/src/components/QuizHosting/QuestionCreator/QuestionCreator.tsx
- quizmaster-client-app/src/components/QuizHosting/QuizWizard.tsx
> Prevent quiz master progressing without adding a question

- quizmaster-client-app/src/components/QuizHosting/QuestionCreator/QuestionCreator.test.tsx
> Fix component updates causing test errors by adding act

- QuizMaster.Api/Controllers/QuizzesController.cs
- quizmaster-client-app/src/components/QuizParticipating/QuizJoiner.tsx
The motivation for this change is to be able the allow the quiz joiner to see the quiz name before joining the quiz.
closes #54
> Fix join quiz title

- quizmaster-client-app/src/components/HomePage/HomePage.tsx
- quizmaster-client-app/src/components/QuizHosting/QuizWizard.tsx
Moved key to URL so that the quiz master can save it for later.
closes #61
> Moved key to URL

- quizmaster-client-app/src/components/QuizHosting/QuizHoster.tsx
check done when each participant answer received to mark as complete if all answers are in
> fix(webapp): stop QM timer when all answers in

- QuizMaster.Api/Startup.cs
Restrict transport type to long polling for testing purposes.
> Limit transport to long polling

- quizmaster-client-app/src/components/QuizHosting/QuestionMarker.tsx
On Quiz Marker screen
Manual verifications and de-verifications are now remembered when new responses arrive.  
Fixes #68
> fix(webapp): quiz marker remember manual verifications and de-verifications

- QuizMaster.Api/Controllers/QuizzesController.cs
- QuizMaster.Api/SignalR/QuizHub.cs
- QuizMaster.Application/QuizMasterMessage.cs
- QuizMaster.Application/Quizzes/Reset.cs
- quizmaster-client-app/src/components/Common/QuizMasterMessage.ts
- quizmaster-client-app/src/components/QuizHosting/HostLobby.tsx
- quizmaster-client-app/src/components/QuizHosting/QuizHoster.tsx
- quizmaster-client-app/src/components/QuizHosting/QuizWizard.tsx
- quizmaster-client-app/src/components/QuizParticipating/QuestionResponder.tsx
Added reset button to QuizWizard page, reset button will
- delete contestants from database
- refresh contestants table for QM
- send message to contestants to kick them out of quiz
Closes #70
> feat(webapp): Reset Participants button for Quiz Wizard

- quizmaster-client-app/src/components/QuizHosting/QuestionMarker.tsx
Fixes #78 
Fixed code to correctly handle the following cases
- Quiz master marks an incorrect answer as correct, it no longer makes everything incorrect
- Quiz master has marked answers as incorrect or correct, and then a new answer arrives,  it no longer resets anything
Auto-accept of an answer is now case-insensitive i.e. "Apple" auto marked as correct where answer is "apple"
> fix(webapp): Fixed marker buttons and auto marking

- quizmaster-client-app/src/app/layout/Layout.test.tsx
- quizmaster-client-app/src/components/Common/Header.tsx
- quizmaster-client-app/src/components/HomePage/HomePage.test.tsx
- quizmaster-client-app/src/components/QuizHosting/QuestionCreator/QuestionInitialiser.test.tsx
> disabled coffee icon button on the homepage

- quizmaster-client-app/src/components/QuizHosting/QuestionCreator/QuestionInitialiser.tsx
> Removed autofocus from answer field in QuizInitialiser

- QuizMaster.Api/Controllers/QuizzesController.cs
- QuizMaster.Application/Quizzes/Details.cs
- QuizMaster.Application/Quizzes/Update.cs
- QuizMaster.Domain/Quiz.cs
- QuizMaster.Domain/QuizState.cs
- QuizMaster.Persistence/Migrations/20201227205212_QuizState.Designer.cs
- QuizMaster.Persistence/Migrations/20201227205212_QuizState.cs
- quizmaster-client-app/src/components/Common/QuizState.ts
- quizmaster-client-app/src/components/QuizHosting/QuizHoster.tsx
- quizmaster-client-app/src/components/QuizHosting/QuizWizard.tsx
- quizmaster-client-app/src/components/QuizParticipating/QuizJoiner.tsx
Quiz DB object now includes QuestionNo and QuizState which are updated as the Quiz Master moves the Quiz along. 
If a participant tries to join a quiz which has already started they will received a sorry message and be unable to join. 
Fixes #79
> fix(webapp):  Added Quiz State in persistence model to handle Latecomer participants

- quizmaster-client-app/src/app/layout/Layout.tsx
> Removed custom MUI CSS media query breakpoint

- QuizMaster.Application/ContestantScore.cs
- QuizMaster.Application/QuizMasterMessage.cs
- quizmaster-client-app/src/components/Common/QuizMasterMessage.ts
- quizmaster-client-app/src/components/QuizHosting/QuizHoster.tsx
- quizmaster-client-app/src/components/QuizParticipating/QuestionResponder.tsx
When the quiz is finished the participants now see the Final Standings table that the Quiz Master sees.  
Resolves #74
> Paricipants can see Final Standings at the end of the quiz session

- quizmaster-client-app/src/components/HomePage/HomePage.tsx
> added a catch method to onJoinQuizSubmit method (Homepage)

- quizmaster-client-app/src/components/QuizParticipating/QuestionResponder.tsx
Set retry policy to try to reconnect every second up to 10 seconds - without this, there are issues reconnecting quickly enough (or at all).
closes #87
> Set retry policy explicitly

- quizmaster-client-app/src/components/QuizParticipating/QuestionResponder.tsx
A couple of updates to help the app reconnect - to test on QA before committing to a fix.
> fix(webapp): reconnect after disconnect and retry up to 30s

- quizmaster-client-app/src/components/QuizHosting/QuizStandings.tsx
> Reduced the minWidth value for the final standings table

- quizmaster-client-app/src/components/QuizHosting/QuestionCreator/TableFieldEditor.tsx
> Added conditional rendering to autoFocus prop

- quizmaster-client-app/src/components/QuizHosting/QuizHoster.tsx
- quizmaster-client-app/src/components/QuizHosting/QuizWizard.tsx
- quizmaster-client-app/src/components/QuizParticipating/QuestionResponder.tsx
Temporary solution whilst awaiting the more complete solution for #89 
Reduced default of 120 seconds to 45 seconds
Also url encodes the quiz name so the link can be shared successfully
> feat(webapp): Reduced default answer time to 45 seconds

- QuizMaster.Api/Postman Tests/Quiz Master API Tests.postman_collection.json
- QuizMaster.Api/Postman Tests/Staging QuizMaster.postman_environment.json
Changed to correct URL for staging environment
Added new API test "Start Quiz" to update quiz status
> test(api): Fixed API tests 

- quizmaster-client-app/src/components/QuizHosting/QuestionCreator/QuestionCreator.tsx
- quizmaster-client-app/src/components/QuizHosting/QuestionCreator/QuestionInitialiser.tsx
- quizmaster-client-app/src/components/QuizHosting/QuestionCreator/TableFieldEditor.tsx
> Changed styling for the Q&A form and Material Table

- quizmaster-client-app/src/components/Common/AboutModal.tsx
This affects what you see when you click ABOUT in the header. 
As well as adding an FAQ, I changed the title and stylings slightly
Resolves #140
> Added FAQ to About Modal

- quizmaster-client-app/src/components/QuizParticipating/QuestionResponder.tsx
Textfield also changes to error with helper text. Closes #144
> Added logic so that quiz participants cannot submit blank answer

- quizmaster-client-app/src/components/QuizHosting/QuizHoster.tsx
> feat(webapp): added in logic to render fragment when quiz starts

- quizmaster-client-app/src/components/QuizHosting/QuizHoster.tsx
> Answer marking switch: incorrect flash fix

- quizmaster-client-app/src/components/QuizHosting/QuestionCreator/QuestionInitialiser.tsx
Fix for new feature: update title and remove question generator button if a question has been added to a quiz manually.
Closes #171
> Question generator fix

- quizmaster-client-app/src/components/QuizHosting/QuizHoster.tsx
Increase time limit to accommodate for slow people
> Increase time limit to accommodate for slow people

- quizmaster-client-app/src/components/Common/QuizStandings.tsx
- quizmaster-client-app/src/components/QuizHosting/QuizPlaying/QuizHoster.tsx
- quizmaster-client-app/src/components/QuizParticipating/ParticipantLobby.tsx
> Minor compiler warnings fix

- quizmaster-client-app/src/components/QuizHosting/QuizCreating/QuizWizard.tsx
> Put the Quiz Master url in it's own element

- quizmaster-client-app/src/components/QuizHosting/QuizCreating/QuizOptions.tsx
Fixed issue where floating point values were not 
Fixes #200
> fix(webapp): Fixed validation of integer values for answer time

- quizmaster-client-app/src/components/QuizHosting/QuizCreating/QuestionCreator/GenerateQuestionsModal.tsx
- quizmaster-client-app/src/components/QuizHosting/QuizCreating/QuestionCreator/QuestionCreator.tsx
- quizmaster-client-app/src/components/QuizHosting/QuizCreating/QuestionCreator/QuestionInitialiser.tsx
When you click Create 10 Questions you will see a modal with a disclaimer about the quality of the questions.  At this point you can cancel or confirm. 
Resolves #203 
Also fixed an issue whereby refreshing the page after generating the questions  the Create 10 questions button would reappear
Fixes #184
> feat(webapp): Added disclaimer for generating questions

- quizmaster-client-app/src/components/QuizHosting/QuizCreating/QuestionCreator/GenerateQuestionsModal.tsx
> fix(webapp): Fixed spelling
